#!/usr/bin/env bash
# Acceptance: multi-backend Onboarding wiring + compute-use integration.
# Structural grep guard — catches a future PR breaking the frontend↔Rust contract.
# Run: bash tests/acceptance/onboarding-backend-e2e.sh
set -uo pipefail
cd "$(dirname "$0")/../.."

PASS=0; FAIL=0
ok()   { echo "  ✅ $1"; PASS=$((PASS+1)); }
no()   { echo "  ❌ $1"; FAIL=$((FAIL+1)); }
check(){ if eval "$2" >/dev/null 2>&1; then ok "$1"; else no "$1"; fi; }

echo "── Onboarding 多后端接线 ──"
check "types.ts 定义 BackendChoice"                "grep -q 'BackendChoice' src/types.ts"
check "Onboarding onComplete 带 backend+skin 参数"   "grep -q 'onComplete: (choice: ShortcutChoice, backend: BackendChoice, skin: SkinId)' src/components/Onboarding.tsx"
check "Onboarding 有 BACKENDS 选项数组"              "grep -q 'const BACKENDS' src/components/Onboarding.tsx"
check "onComplete 调用传 selected+backend+skin"     "grep -q 'onComplete(selected, backend, skin)' src/components/Onboarding.tsx"
check "OnboardingView 把 backend+skin 传给 save_shortcut" "grep -q 'save_shortcut.*{ choice, backend, skin }' src/OnboardingView.tsx"

echo "── Rust 后端契约 ──"
check "save_shortcut 接收 backend 参数"             "grep -q 'backend: String' src-tauri/src/commands.rs"
check "Backend::from_choice 存在"                  "grep -q 'pub fn from_choice' src-tauri/src/backend.rs"
check "config.rs 有 backend 字段"                  "grep -q 'pub backend: Backend' src-tauri/src/config.rs"
check "三后端枚举齐全"                              "grep -q 'ClaudeCli' src-tauri/src/backend.rs && grep -q 'CodexCli' src-tauri/src/backend.rs && grep -q 'OpenclawCli' src-tauri/src/backend.rs"

echo "── compute use (agent-browser) ──"
check "BROWSER_CAPABILITY_PROMPT 存在"             "grep -q 'BROWSER_CAPABILITY_PROMPT' src-tauri/src/claude_cli.rs"
check "system_prompt() 检测 agent-browser"         "grep -q 'find_binary(\"agent-browser\")' src-tauri/src/claude_cli.rs"
check "claude_cli 用 system_prompt() 而非常量"      "grep -q 'sys_prompt' src-tauri/src/claude_cli.rs"
check "backend.rs 各后端用 system_prompt()"        "grep -q 'crate::claude_cli::system_prompt()' src-tauri/src/backend.rs"

echo "── 桌宠皮肤系统 (v0.1.7) ──"
check "src/skins.ts 定义 6 款 skin"             "grep -c '^  {' src/skins.ts | grep -q '^6$'"
check "Rust skins.rs 有 6 个 SkinId 枚举值"      "grep -E '^    (Classic|Lab|Field|Ninja|Cyber|Golden),' src-tauri/src/skins.rs | wc -l | tr -d ' ' | grep -q '^6$'"
check "config.rs 有 skin 字段"                   "grep -q 'pub skin: SkinId' src-tauri/src/config.rs"
check "CURRENT_CONFIG_VERSION = 11"               "grep -q 'CURRENT_CONFIG_VERSION: u32 = 11' src-tauri/src/config.rs"
check "save_shortcut 接收 skin 参数"             "grep -q 'skin: Option<String>' src-tauri/src/commands.rs"
check "save_skin / get_skin 命令存在"             "grep -q 'pub fn save_skin' src-tauri/src/commands.rs && grep -q 'pub fn get_skin' src-tauri/src/commands.rs"
check "tray 有皮肤子菜单"                          "grep -q 'skin-submenu' src-tauri/src/tray.rs"
check "events.rs 有 EV_SKIN_CHANGED"             "grep -q 'EV_SKIN_CHANGED' src-tauri/src/events.rs"
check "Onboarding 是 4 步 (1|2|3|4)"            "grep -q 'useState<1 | 2 | 3 | 4>' src/components/Onboarding.tsx"
check "Onboarding 引入 SKINS"                    "grep -q 'import { SKINS' src/components/Onboarding.tsx"
check "onComplete 带 skin 参数"                   "grep -q 'onComplete: (choice: ShortcutChoice, backend: BackendChoice, skin: SkinId)' src/components/Onboarding.tsx"
check "OnboardingView 把 skin 传给 save_shortcut" "grep -q 'save_shortcut.*{ choice, backend, skin }' src/OnboardingView.tsx"
check "App.tsx 订阅 EV_SKIN_CHANGED"             "grep -q 'EV_SKIN_CHANGED' src/App.tsx"
check "App.tsx 传 skin 给 PixelMouse"            "grep -q 'skin={skin}' src/App.tsx"
check "PixelMouse 接 skin prop"                  "grep -q 'skin?: SkinId' src/components/PixelMouse.tsx"
check "DESIGN.md 加 Skin Palettes 表"             "grep -q 'Skin Palettes' DESIGN.md"

echo "── P0a · 浏览器桥接（CDP + chrome-devtools-mcp） ──"
check "browser_bridge.rs 存在"                    "test -f src-tauri/src/browser_bridge.rs"
check "lib.rs 注册 browser_bridge 模块"            "grep -q 'pub mod browser_bridge' src-tauri/src/lib.rs"
check "CDP_PORT = 9222 (生态对齐)"                "grep -q 'pub const CDP_PORT: u16 = 9222' src-tauri/src/browser_bridge.rs"
check "debug profile 隔离在 .mouseclaw/"          "grep -q '.mouseclaw/chrome-debug-profile' src-tauri/src/browser_bridge.rs"
check "chrome-devtools-mcp 注册命令"               "grep -q 'chrome-devtools-mcp@latest' src-tauri/src/browser_bridge.rs"
check "enable_browser_automation 命令注册"         "grep -q 'enable_browser_automation' src-tauri/src/lib.rs"
check "capability_status 命令存在"                 "grep -q 'pub fn capability_status' src-tauri/src/commands.rs"
check "tray 有「启用浏览器自动化」菜单"             "grep -q 'enable-browser' src-tauri/src/tray.rs"
check "CHROME_CDP_CAPABILITY_PROMPT 存在"          "grep -q 'CHROME_CDP_CAPABILITY_PROMPT' src-tauri/src/claude_cli.rs"
check "system_prompt 走 3 档分支"                  "grep -q 'cdp_alive' src-tauri/src/claude_cli.rs"

echo "── P0b · Mode B 剪贴板 fallback（富文本编辑器） ──"
check "RICH_EDITOR_BUNDLES 列表存在"               "grep -q 'RICH_EDITOR_BUNDLES' src-tauri/src/mode_b.rs"
check "Slack / Notion / VSCode 在 fallback 名单"  "grep -q 'tinyspeck.slackmacgap' src-tauri/src/mode_b.rs && grep -q 'notion.id' src-tauri/src/mode_b.rs && grep -q 'microsoft.VSCode' src-tauri/src/mode_b.rs"
check "paste_via_clipboard 实现存在"               "grep -q 'fn paste_via_clipboard' src-tauri/src/mode_b.rs"
check "Cmd+V 合成路径走 CGEventFlagCommand"        "grep -q 'CGEventFlagCommand' src-tauri/src/mode_b.rs"
check "should_use_clipboard_paste 路由函数"        "grep -q 'fn should_use_clipboard_paste' src-tauri/src/mode_b.rs"

echo "── P1 · 系统状态窗 ──"
check "StatusView.tsx 存在"                        "test -f src/StatusView.tsx"
check "tray 注册 status 菜单"                      "grep -q '\"status\"' src-tauri/src/tray.rs"
check "open_status_window 在 tray"                 "grep -q 'fn open_status_window' src-tauri/src/tray.rs"
check "main.tsx 路由 status"                       "grep -q 'view === \"status\"' src/main.tsx"
check "capabilities 加 status 窗口"                "grep -q '\"status\"' src-tauri/capabilities/default.json"
check "StatusView 用 capability_status"            "grep -q 'capability_status' src/StatusView.tsx"

echo "── v0.1.8 UX · 不自动消失 / 气泡滚动 / 跟随鼠标 ──"
check "短回复 30s 自动消失 / 长回复不自动消失"        "grep -q 'auto-hide 3s 太激进' src-tauri/src/pipeline.rs"
check "bubble-scroll CSS 存在"                       "grep -q '.bubble-scroll' src/components/Bubble.css"
check "Bubble 接 scrollable prop"                    "grep -q 'scrollable?: boolean' src/components/Bubble.tsx"
check "App.tsx 给长回复气泡设 scrollable"            "grep -q 'scrollable={long}' src/App.tsx"
check "cursor_follow 模块存在"                        "test -f src-tauri/src/cursor_follow.rs"
check "AppState 有 follow_cursor 字段"                "grep -q 'follow_cursor: AtomicBool' src-tauri/src/lib.rs"
check "lib.rs spawn cursor follow loop"               "grep -q 'spawn_follow_loop' src-tauri/src/lib.rs"
check "overlay::reposition_to_cursor 存在"           "grep -q 'pub fn reposition_to_cursor' src-tauri/src/overlay.rs"
check "emit_view 进非 listening 状态时停止跟随"      "grep -q 'should_follow = matches!' src-tauri/src/overlay.rs"

echo "── v0.1.8 P3 · Whisper 模型可切换 ──"
check "config 有 WhisperModel 枚举"                  "grep -q 'pub enum WhisperModel' src-tauri/src/config.rs"
check "默认 Small"                                    "grep -q 'WhisperModel::Small' src-tauri/src/config.rs"
check "CURRENT_CONFIG_VERSION = 11"                    "grep -q 'CURRENT_CONFIG_VERSION: u32 = 11' src-tauri/src/config.rs"
check "save_whisper_model 命令"                       "grep -q 'pub fn save_whisper_model' src-tauri/src/commands.rs"
check "托盘有「🎙️ 语音模型」子菜单"                  "grep -q 'whisper-submenu' src-tauri/src/tray.rs"
check "tray 处理 whisper:* event"                     "grep -q 'strip_prefix(\"whisper:\")' src-tauri/src/tray.rs"
check "transcribe::set_active_model 存在"             "grep -q 'pub fn set_active_model' src-tauri/src/transcribe.rs"

echo "── v0.1.9 · Bug 修 + markdown ──"
check "bubble-scroll 加了 display:block 强制"        "grep -q 'display: block !important' src/components/Bubble.css"
check "Bubble 接 markdown prop"                      "grep -q 'markdown?: boolean' src/components/Bubble.tsx"
check "marked 已装"                                   "grep -q 'marked' package.json"
check "App.tsx reply 气泡传 markdown"                "grep -q 'markdown' src/App.tsx"
check "Panel 按钮文案变「继续追问」"                  "grep -q '继续追问' src/components/Bubble.tsx || grep -q 'Continue chat' src/components/Bubble.tsx || grep -q 'bubble.expand_to_panel' src/components/Bubble.tsx"

echo "── v0.1.9 · i18n 框架 ──"
check "src/i18n/types.ts 存在"                       "test -f src/i18n/types.ts"
check "src/i18n/zh.ts 存在"                          "test -f src/i18n/zh.ts"
check "src/i18n/en.ts 存在"                          "test -f src/i18n/en.ts"
check "src/i18n/index.ts 导出 useT"                  "grep -q 'export function useT' src/i18n/index.ts"
check "i18n 支持插值 {key}"                          "grep -q 'interpolate' src/i18n/index.ts"
check "save_language Rust 命令"                      "grep -q 'pub fn save_language' src-tauri/src/commands.rs"
check "get_language Rust 命令"                       "grep -q 'pub fn get_language' src-tauri/src/commands.rs"
check "events.rs 有 EV_LANG_CHANGED"                 "grep -q 'EV_LANG_CHANGED' src-tauri/src/events.rs"
check "config.rs 加 language 字段"                   "grep -q 'pub language: String' src-tauri/src/config.rs"
check "tray 有「🌐 语言」子菜单"                     "grep -q 'lang-submenu' src-tauri/src/tray.rs"
check "Onboarding 用 useT"                           "grep -q 'useT' src/components/Onboarding.tsx"
check "StatusView 用 useT"                           "grep -q 'useT' src/StatusView.tsx"
check "Bubble 用 useT"                               "grep -q 'useT' src/components/Bubble.tsx"

echo "── v0.1.10 · Whisper i18n + Tidy-up + Hub UI ──"
check "Whisper 用 ui_lang 决定语言"               "grep -q 'ui_lang' src-tauri/src/transcribe.rs"
check "中文加简体引导 prompt"                       "grep -q '以下是普通话的句子' src-tauri/src/transcribe.rs"
check "tidy_up 模块存在"                          "test -f src-tauri/src/tidy_up.rs"
check "tidy_up_enabled 在 config"                "grep -q 'tidy_up_enabled' src-tauri/src/config.rs"
check "pipeline 调用 tidy"                        "grep -q 'tidy_up::tidy' src-tauri/src/pipeline.rs"
check "save_tidy_up 命令注册"                     "grep -q 'save_tidy_up' src-tauri/src/lib.rs"
check "托盘有 toggle-tidy"                        "grep -q 'toggle-tidy' src-tauri/src/tray.rs"
check "Hub 组件存在"                              "test -f src/components/Hub.tsx"
check "Hub CSS 存在"                              "test -f src/components/Hub.css"
check "App.tsx 点桌宠开 Hub"                       "grep -q 'setHubOpen' src/App.tsx"
check "Hub 用 list_clipboard"                     "grep -q 'list_clipboard' src/components/Hub.tsx"

echo "── v0.1.11 · 分层 tidy（regex 默认开 + LLM opt-in）──"
check "voice_ime.rs · CGEventTap fn 监听"           "test -f src-tauri/src/voice_ime.rs && grep -q 'CGEventTapCreate' src-tauri/src/voice_ime.rs"
check "FN_FLAG = 1<<23 (NSEventModifierFlagFunction)"  "grep -q 'FN_FLAG: u64 = 1 << 23' src-tauri/src/voice_ime.rs"
check "LONG_PRESS_MS = 300ms"                          "grep -q 'LONG_PRESS_MS: u128 = 300' src-tauri/src/voice_ime.rs"
check "voice_ime_enabled 在 config"                    "grep -q 'voice_ime_enabled' src-tauri/src/config.rs"
check "save_voice_ime 命令注册"                         "grep -q 'save_voice_ime' src-tauri/src/lib.rs"
check "托盘有 toggle-voice-ime"                         "grep -q 'toggle-voice-ime' src-tauri/src/tray.rs"
check "lib.rs spawn voice_ime"                          "grep -q 'voice_ime::spawn' src-tauri/src/lib.rs"
check "light_clean 函数存在"                       "grep -q 'pub fn light_clean' src-tauri/src/tidy_up.rs"
check "ZH_FILLERS 包含口头禅"                       "grep -q 'ZH_FILLERS' src-tauri/src/tidy_up.rs"
check "EN_FILLER_PATTERNS 用 regex"                  "grep -q 'EN_FILLER_PATTERNS' src-tauri/src/tidy_up.rs"
check "pipeline 永远跑 light_clean"                  "grep -q 'tidy_up::light_clean' src-tauri/src/pipeline.rs"
check "LLM tidy 默认关 (default false)"              "grep -q 'fn default_tidy_up.*bool.*false' src-tauri/src/config.rs"
check "regex crate 已加"                             "grep -q '^regex' src-tauri/Cargo.toml"
echo "── 构建 / 测试闸门 ──"
check "前端 bun build 通过"                         "bun run build"
check "Rust cargo check 通过"                       "cargo check --manifest-path src-tauri/Cargo.toml"
check "Rust 单元测试通过"                           "cargo test --manifest-path src-tauri/Cargo.toml --lib"

echo
echo "════════ $PASS passed, $FAIL failed ════════"
[ "$FAIL" -eq 0 ] && exit 0 || exit 1
